apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "anraghuncluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "anraghuncluster"
    spec:
      containers:
        - name: "anraghuncluster"
          image: "anraghuncr.azurecr.io/anraghuncluster"
          ports:
          - containerPort: 1337