apiVersion: v1
kind: Service
metadata:
    name: "anraghuncluster2"
    labels:
        app: "anraghuncluster2"
spec:
    type: LoadBalancer
    ports:
    - port: 1337
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "anraghuncluster2"